### PR TITLE
Add Italian translation

### PR DESCRIPTION
**Pull request by Kappa971**
Hi, I created the Italian translation for the Classics Patch, I hope I didn't make too many mistakes 😅
To start I used the Russian translation files because I have no idea how to extract the strings.

I noticed a bug in The First Encounter where the special character `è` is displayed incorrectly. I used the `Windows-1252` codepage, which is what the official translation files also seem to use, but that character is displayed as in the screenshot below:
image
The same thing happens with the strings of the official translation.
Other special characters are displayed correctly:
image

Works well in The Second Encounter:
image

I share the package: [SE1_ClassicsPatch_ITA.zip](https://github.com/user-attachments/files/16838725/SE1_ClassicsPatch_ITA.zip)

### CODE REVIEW

**Comment by DreamyCecil** [comment]
I may put this off until the next release, which will add a few more strings. And I'll try to add tools for extracting/updating the strings by then.

**Comment by DreamyCecil** [comment]
I'm preparing a new release right now and I would prefer if you could rebase your fork and recommit new files, if you can.

New lines to translate before committing:
- Description files under `ITA/Controls`
- New strings under `ITA/Data/Translations` (28 lines marked with `$TODO$` in all files)

To create new localizations, follow the instructions under `Localization/README.md`.
Though you don't have to do it from scratch, because I've updated your localization files manually before this release: [ITA.zip](https://github.com/user-attachments/files/17168200/ITA.zip)

**Comment by Kappa971** [comment]
I should be able to update the translation by tomorrow. Thanks

**Comment by Kappa971** [comment]
I think that's all. I hope there aren't too many mistakes, if there are I hope they will be reported or corrected by other people.

**Comment by DreamyCecil** [comment]
Thanks.

**Pull request merged**
